### CREATE a new contact (local)
POST http://localhost:3000/newContact HTTP/1.1
content-type: application/json

{
    "firstName": "Jack",
    "lastName": "Skellington",
    "email": "jayskelly@gmail.com",
    "favoriteColor": "black",
    "birthday": "October 31"
}


### UPDATE a single contact (local)
PUT http://localhost:3000/updateContact/*** HTTP/1.1


### DELETE a single contact (local)
DELETE http://localhost:3000/deleteContact/*** HTTP/1.1


### RENDER CREATE a new contact
POST https://cse341-75b7.onrender.com/newContact HTTP/1.1
content-type: application/json

{
    "firstName": "Sally",
    "lastName": "Skellington",
    "email": "sallyskelly@gmail.com",
    "favoriteColor": "pink",
    "birthday": "September 30"
}

### RENDER UPDATE a single contact
PUT https://cse341-75b7.onrender.com/updateContact/*** HTTP/1.1


### RENDER DELETE a single contact
DELETE https://cse341-75b7.onrender.com/deleteContact/*** HTTP/1.1 
